### PR TITLE
Added border width and properties made visible for IB

### PR DESCRIPTION
**Pull request by bozongiggsa**
Now user can adjust border width and setup all properties at "properties" tab in Interface Builder

### CODE REVIEW

**Comment by reesemclean** [comment]
Thanks!

**Comment by reesemclean** [comment]
Feel free to update the readme - the part about interface builder.

**Comment by bozongiggsa** [comment]
Ok, I'll update readme.

**Comment by bozongiggsa** [comment]
Could you please update CocoaPod?

**Comment by reesemclean** [comment]
It is updated... v1.1.0, let me know if it doesn't work for some reason.

**Comment by bozongiggsa** [comment]
Thanks a lot! It was updated successfully.

Does the file **RDMBorderedButton.podspec** need to be updated? There is still '1.0.0' inside.

**Comment by reesemclean** [comment]
Yes it should've been. I just forgot to push it—just updated it. Shouldn't effect anything for you.

**Pull request merged**
